import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL='https://gzclvhcvsfcslilxaiyg.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Y2x2aGN2c2Zjc2xpbHhhaXlnIiwicm9sZSI6IkFub24iLCJpYXQiOjE3ODYwMjUyMjAsImV4cCI6MjEwMTYwMTIyMH0.8gD4bwPpxdLl9kGtPVCRRPylEsES_DHWH4KhKDJvzuE';
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); const tg=window.Telegram?.WebApp; const $=id=>document.getElementById(id); const page=()=>$('pageContainer');
let checkoutMode=null,buyNowItem=null,cartSelection=new Set(),previousPage='home';
function toast(m){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.classList.add('show'),10);setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),300)},3000)}
function readCart(){try{const v=JSON.parse(localStorage.getItem('cart')||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function writeCart(c){localStorage.setItem('cart',JSON.stringify(c));const b=$('cartCount');const n=c.reduce((s,i)=>s+Number(i.quantity||0),0);if(b){b.textContent=n;b.style.display=n?'inline':'none'}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function title(t){if($('pageTitle'))$('pageTitle').textContent=t;if($('backBtn'))$('backBtn').style.display='flex'}
function selectedItems(){const c=readCart();return c.filter((_,i)=>cartSelection.has(String(i)))}
function checkoutHtml(items,total){return `<div style="padding:14px 12px 100px"><div style="display:flex;align-items:center;gap:10px;margin-bottom:14px"><button type="button" id="checkoutBack" style="border:0;background:var(--tg-secondary-bg,#f2f2f2);border-radius:50%;width:40px;height:40px;font-size:18px">←</button><div><div style="font-size:20px;font-weight:800">ពិនិត្យការបញ្ជាទិញ</div><div style="font-size:12px;color:var(--tg-hint)">សូមពិនិត្យព័ត៌មានមុនដាក់បញ្ជា</div></div></div><div style="background:var(--tg-section-bg,#fff);border-radius:16px;padding:12px;margin-bottom:12px">${items.map(i=>`<div style="display:flex;gap:10px;padding:8px 0;border-bottom:1px solid var(--tg-section-separator-color,#eee)"><img src="${esc(i.image_url||'')}" style="width:64px;height:64px;object-fit:cover;border-radius:10px;background:#f3f3f3" onerror="this.style.display='none'"><div style="flex:1"><div style="font-weight:700">${esc(i.product_name)}</div><div style="font-size:12px;color:var(--tg-hint)">ទំហំ ${esc(i.size)} · ${esc(i.color)} · x${Number(i.quantity)}</div><div style="font-weight:800;margin-top:4px">$${(Number(i.price)*Number(i.quantity)).toFixed(2)}</div></div></div>`).join('')}<div style="display:flex;justify-content:space-between;padding-top:12px;font-weight:800"><span>សរុប</span><span>$${total.toFixed(2)}</span></div></div><form id="checkoutForm"><div style="background:var(--tg-section-bg,#fff);border-radius:16px;padding:14px;margin-bottom:12px"><div style="font-weight:800;margin-bottom:10px">ព័ត៌មានដឹកជញ្ជូន</div><label class="form-label">ឈ្មោះ</label><input class="form-input" id="checkoutName" required><label class="form-label">លេខទូរស័ព្ទ</label><input class="form-input" id="checkoutPhone" type="tel" required><label class="form-label">អាសយដ្ឋាន</label><textarea class="form-input" id="checkoutAddress" rows="3" required></textarea></div><div style="background:var(--tg-section-bg,#fff);border-radius:16px;padding:14px;margin-bottom:12px"><div style="font-weight:800;margin-bottom:10px">វិធីបង់ប្រាក់</div><select class="form-input" id="checkoutPayment"><option value="khqr">KHQR</option><option value="cash">ទូទាត់ពេលទទួលទំនិញ</option></select><div id="khqrNotice" style="margin-top:10px;padding:12px;border-radius:12px;background:#f6f6f6;font-size:13px;color:var(--tg-hint)">បន្ទាប់ពីដាក់បញ្ជា សូមបង់តាម KHQR របស់ហាង និងផ្ញើភស្តុតាងទៅអ្នកគ្រប់គ្រង។</div></div><button type="submit" class="btn-primary btn-success" style="width:100%;font-size:16px;padding:14px">ដាក់បញ្ជាទិញ · $${total.toFixed(2)}</button></form></div>`}
function showCheckout(items,mode,back){checkoutMode=mode;buyNowItem=mode==='buy-now'?items[0]:null;previousPage=back;title(mode==='buy-now'?'បញ្ជាទិញឥឡូវនេះ':'បញ្ជាទិញ');const total=items.reduce((s,i)=>s+Number(i.price)*Number(i.quantity),0);page().innerHTML=checkoutHtml(items,total);$('checkoutBack')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(previousPage==='cart')renderCartFixed();else window.history.back()});$('checkoutPayment')?.addEventListener('change',e=>{$('khqrNotice').style.display=e.target.value==='khqr'?'block':'none'});window.scrollTo(0,0)}
function cartItem(i,idx){return `<div style="display:flex;gap:10px;padding:12px 4px;border-bottom:1px solid var(--tg-section-separator-color,#eee);align-items:center"><input class="cart-select" data-index="${idx}" type="checkbox" checked><img src="${esc(i.image_url||'')}" style="width:68px;height:68px;object-fit:cover;border-radius:10px;background:#f3f3f3" onerror="this.style.display='none'"><div style="flex:1"><div style="font-weight:700">${esc(i.product_name)}</div><div style="font-size:12px;color:var(--tg-hint)">${esc(i.size)} · ${esc(i.color)}</div><div style="display:flex;align-items:center;gap:7px;margin-top:6px"><button class="qty-minus" data-index="${idx}">−</button><span>${Number(i.quantity)}</span><button class="qty-plus" data-index="${idx}">+</button><strong style="margin-left:auto">$${(Number(i.price)*Number(i.quantity)).toFixed(2)}</strong></div></div><button class="cart-delete" data-index="${idx}" style="border:0;background:none;font-size:18px">🗑️</button></div>`}
function renderCartFixed(){const c=readCart();title('កន្ត្រកទំនិញ');if(!c.length){page().innerHTML='<div style="text-align:center;padding:60px 20px;color:var(--tg-hint)"><div style="font-size:48px">🛒</div><p>កន្ត្រករបស់អ្នកនៅទទេ</p></div>';return}cartSelection=new Set(c.map((_,i)=>String(i)));const total=c.reduce((s,i)=>s+Number(i.price)*Number(i.quantity),0);page().innerHTML=`<div style="padding:12px 12px 110px"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><b style="font-size:20px">កន្ត្រក</b><label><input type="checkbox" id="selectAllCart" checked> ជ្រើសរើសទាំងអស់</label></div>${c.map(cartItem).join('')}<div style="position:fixed;left:0;right:0;bottom:0;padding:10px 12px;background:var(--tg-bg-color,#fff);border-top:1px solid #ddd;display:flex;gap:10px;align-items:center;z-index:30"><div><small>សរុប</small><br><b id="cartSelectedTotal">$${total.toFixed(2)}</b></div><button id="fixedCartCheckout" class="btn-primary btn-success" style="flex:1">ទិញឥឡូវនេះ</button></div></div>`;bindCart()}
function updateTotal(){const c=readCart(),t=c.reduce((s,i,n)=>s+(cartSelection.has(String(n))?Number(i.price)*Number(i.quantity):0),0);if($('cartSelectedTotal'))$('cartSelectedTotal').textContent='$'+t.toFixed(2);if($('selectAllCart'))$('selectAllCart').checked=cartSelection.size===c.length}
function bindCart(){const stop=e=>e.stopPropagation();page().querySelectorAll('input,button,label').forEach(x=>x.addEventListener('click',stop));$('selectAllCart')?.addEventListener('change',e=>{e.stopPropagation();cartSelection=e.target.checked?new Set(readCart().map((_,i)=>String(i))):new Set();page().querySelectorAll('.cart-select').forEach(x=>x.checked=e.target.checked);updateTotal()});page().querySelectorAll('.cart-select').forEach(x=>x.addEventListener('change',e=>{if(e.target.checked)cartSelection.add(e.target.dataset.index);else cartSelection.delete(e.target.dataset.index);updateTotal()}));page().querySelectorAll('.cart-delete').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const c=readCart();c.splice(+x.dataset.index,1);writeCart(c);renderCartFixed();toast('បានលុបទំនិញចេញពីកន្ត្រក')}));page().querySelectorAll('.qty-minus,.qty-plus').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const c=readCart(),i=c[+x.dataset.index];if(!i)return;i.quantity=x.classList.contains('qty-minus')?Math.max(1,+i.quantity-1):Math.min(+(i.max_stock||999999),+i.quantity+1);writeCart(c);renderCartFixed()}));$('fixedCartCheckout')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const items=selectedItems();if(!items.length)return toast('សូមជ្រើសរើសទំនិញយ៉ាងហោចណាស់មួយ');showCheckout(items,'cart','cart')})}
async function buyNow(){const name=document.querySelector('.product-detail-name')?.textContent?.trim();const size=document.querySelector('.size-btn.selected')?.dataset.size;const color=document.querySelector('.color-btn.selected')?.dataset.color;const qty=Number($('quantityDisplay')?.textContent||1);if(!name||!size||!color)return toast('សូមជ្រើសរើសទំហំ និងពណ៌');const {data:p,error:pe}=await supabase.from('products').select('*').eq('name',name).single();if(pe||!p)return toast('មិនអាចរកផលិតផលបាន');const {data:inv,error:ie}=await supabase.from('inventory').select('*').eq('product_id',p.id).eq('size',size).eq('color',color).single();if(ie||!inv||+inv.quantity<qty)return toast('មិនមានស្តុកគ្រប់គ្រាន់');showCheckout([{inventory_id:inv.id,product_id:p.id,product_name:p.name,size,color,price:p.price,quantity:qty,image_url:p.image_url,max_stock:inv.quantity}],'buy-now','product')}
function injectBuyNow(){const add=$('addToCartBtn');if(!add||$('buyNowDirectBtn'))return;const b=document.createElement('button');b.id='buyNowDirectBtn';b.type='button';b.className='btn-primary';b.style.cssText='width:100%;margin-top:10px;background:#111;color:#fff';b.innerHTML='<i class="fas fa-bolt"></i> បញ្ជាទិញឥឡូវនេះ';add.insertAdjacentElement('afterend',b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();buyNow()})}
async function submitCheckout(e){const f=e.target;if(!(f instanceof HTMLFormElement)||f.id!=='checkoutForm')return;e.preventDefault();e.stopImmediatePropagation();const btn=f.querySelector('button[type=submit]');if(btn)btn.disabled=true;const name=$('checkoutName')?.value.trim(),phone=$('checkoutPhone')?.value.trim(),address=$('checkoutAddress')?.value.trim(),payment=$('checkoutPayment')?.value,user=tg?.initDataUnsafe?.user;if(!name||!phone||!address)return(toast('សូមបំពេញព័ត៌មានឲ្យបានពេញលេញ'),btn&&(btn.disabled=false));if(!user?.id)return(toast('មិនអាចកំណត់អត្តសញ្ញាណ Telegram បាន'),btn&&(btn.disabled=false));const items=checkoutMode==='buy-now'?[buyNowItem]:selectedItems();try{const {data,error}=await supabase.rpc('place_order_atomic',{p_telegram_id:+user.id,p_username:user.username||null,p_first_name:name,p_phone:phone,p_address:address,p_payment_method:payment,p_items:items.map(i=>({inventory_id:i.inventory_id,quantity:+i.quantity}))});if(error)throw error;if(!data?.order_id)throw new Error('ការបញ្ជាទិញមិនបានបញ្ចប់');if(checkoutMode==='cart'){const chosen=new Set(cartSelection);writeCart(readCart().filter((_,i)=>!chosen.has(String(i))))}else writeCart(readCart().filter(i=>i.inventory_id!==buyNowItem.inventory_id));page().innerHTML=`<div style="text-align:center;padding:50px 20px"><div style="font-size:64px">✅</div><h2>បញ្ជាទិញបានជោគជ័យ!</h2><p>លេខបញ្ជា: <b>${esc(data.order_number)}</b></p><p>សរុប: <b>$${Number(data.total||0).toFixed(2)}</b></p><button class="btn-primary" id="orderDone">ត្រឡប់ទៅទំព័រដើម</button></div>`;$('orderDone')?.addEventListener('click',()=>location.reload())}catch(err){console.error(err);toast(err?.message||'មានបញ្ហាក្នុងការបញ្ជាទិញ');if(btn)btn.disabled=false}}
document.addEventListener('submit',submitCheckout,true);
document.addEventListener('click',e=>{const t=e.target.closest?.('#checkoutBtn');if(t){e.preventDefault();e.stopImmediatePropagation();renderCartFixed()}},true);
const obs=new MutationObserver(()=>{if(document.querySelector('.product-detail'))setTimeout(injectBuyNow,0)});obs.observe(document.body,{childList:true,subtree:true});
window.addEventListener('load',()=>setTimeout(injectBuyNow,100));
