import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL='https://gzclvhcvsfcslilxaiyg.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Y2x2aGN2c2Zjc2xpbHhhaXlnIiwicm9sZSI6IkFub24iLCJpYXQiOjE3ODYwMjUyMjAsImV4cCI6MjEw១៦០MTIyMH0.8gD4bwPpxdLl9kGtPVCRRPylEsES_DHWH4KhKDJvzuE';
// The key above is public anon-key material intended for browser use.
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const tg=window.Telegram?.WebApp;
try{tg?.expand();tg?.enableClosingConfirmation();}catch{}
const $=id=>document.getElementById(id); const page=$('pageContainer');
const state={page:'home',products:[],product:null,variant:null,qty:1,cart:[],checkoutMode:null,checkoutItems:[]};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'$'+Number(v||0).toFixed(2);
function toast(m){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},2600)}
function loadCart(){try{const c=JSON.parse(localStorage.getItem('chuchus_cart')||'[]');state.cart=Array.isArray(c)?c:[]}catch{state.cart=[]} updateBadge()}
function saveCart(){localStorage.setItem('chuchus_cart',JSON.stringify(state.cart));updateBadge()}
function updateBadge(){const n=state.cart.reduce((s,i)=>s+Number(i.quantity||0),0);$('cartCount').textContent=n;$('cartCount').style.display=n?'inline-flex':'none'}
function setHeader(title,back=true){$('pageTitle').textContent=title;$('backBtn').style.display=back?'flex':'none'}
function navBack(){if(state.page==='checkout'){render(state.checkoutMode==='cart'?'cart':'product',state.product)}else if(state.page==='product')render('home');else if(state.page==='cart')render('home');else render('home')}
$('backBtn').onclick=e=>{e.preventDefault();e.stopPropagation();navBack()}; $('cartBtn').onclick=e=>{e.preventDefault();e.stopPropagation();render('cart')};
function render(p,data=null){state.page=p;if(p==='home')return renderHome();if(p==='product')return renderProduct(data);if(p==='cart')return renderCart();if(p==='checkout')return renderCheckout();}
async function renderHome(){setHeader('ហាងខោអាវជជុស',false);page.innerHTML='<div class="section-head"><div><h2>ផលិតផល</h2><p>ជ្រើសរើសផលិតផលដែលអ្នកចូលចិត្ត</p></div></div><div id="productsGrid" class="products-grid"><div class="empty-state">កំពុងផ្ទុក...</div></div>';const {data,error}=await supabase.from('products').select('*').order('created_at',{ascending:false});if(error){$('productsGrid').innerHTML='<div class="empty-state">មិនអាចផ្ទុកផលិតផលបាន</div>';return}state.products=data||[];$('productsGrid').innerHTML=state.products.map(p=>`<article class="shop-card" data-id="${esc(p.id)}"><img src="${esc(p.image_url||p.image||'')}" alt="${esc(p.name)}" onerror="this.src='https://placehold.co/600x600?text=No+Image'"><div class="shop-card-body"><h3>${esc(p.name)}</h3><div class="price">${money(p.price)}</div><button class="card-btn" type="button">មើលផលិតផល</button></div></article>`).join('');$('productsGrid').querySelectorAll('.shop-card').forEach(c=>c.onclick=e=>{if(e.target.closest('button')||e.currentTarget.contains(e.target)){const p=state.products.find(x=>String(x.id)===String(c.dataset.id));render('product',p)}})}
async function renderProduct(p){state.product=p;state.qty=1;state.variant=null;setHeader('លម្អិតផលិតផល',true);page.innerHTML='<div class="detail-loading">កំពុងផ្ទុក...</div>';const {data:inv}=await supabase.from('inventory').select('*').eq('product_id',p.id);const rows=inv||[];const sizes=[...new Set(rows.map(x=>x.size).filter(Boolean))];const colors=[...new Set(rows.map(x=>x.color).filter(Boolean))];const image=p.image_url||p.image||'';page.innerHTML=`<section class="product-detail-v2"><img class="hero-product-image" src="${esc(image)}" onerror="this.src='https://placehold.co/800x800?text=No+Image'"><div class="detail-body"><div class="eyebrow">CHUCHUS SHOP</div><h2>${esc(p.name)}</h2><div class="detail-price">${money(p.price)}</div><p class="detail-desc">${esc(p.description||'ផលិតផលគុណភាពសម្រាប់អ្នក។')}</p>${sizes.length?`<div class="choice"><b>ទំហំ</b><div class="choice-row">${sizes.map(s=>`<button type="button" class="choice-btn size-choice" data-value="${esc(s)}">${esc(s)}</button>`).join('')}</div></div>`:''}${colors.length?`<div class="choice"><b>ពណ៌</b><div class="choice-row">${colors.map(c=>`<button type="button" class="choice-btn color-choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div></div>`:''}<div class="choice"><b>ចំនួន</b><div class="qty"><button type="button" id="minus">−</button><strong id="qty">1</strong><button type="button" id="plus">+</button></div></div><div class="buy-actions"><button type="button" id="addCart" class="secondary-action">បន្ថែមទៅកន្ត្រក</button><button type="button" id="buyNow" class="primary-action">⚡ បញ្ជាទិញឥឡូវនេះ</button></div></div></section>`;
let selectedSize=sizes[0]||null,selectedColor=colors[0]||null;const choose=(sel,val)=>{document.querySelectorAll(sel).forEach(b=>b.classList.toggle('selected',b.dataset.value===val))};if(selectedSize)choose('.size-choice',selectedSize);if(selectedColor)choose('.color-choice',selectedColor);page.querySelectorAll('.size-choice').forEach(b=>b.onclick=e=>{e.stopPropagation();selectedSize=b.dataset.value;choose('.size-choice',selectedSize)});page.querySelectorAll('.color-choice').forEach(b=>b.onclick=e=>{e.stopPropagation();selectedColor=b.dataset.value;choose('.color-choice',selectedColor)});$('minus').onclick=e=>{e.stopPropagation();state.qty=Math.max(1,state.qty-1);$('qty').textContent=state.qty};$('plus').onclick=e=>{e.stopPropagation();state.qty=Math.min(99,state.qty+1);$('qty').textContent=state.qty};const getVariant=async()=>{let q=supabase.from('inventory').select('*').eq('product_id',p.id);if(selectedSize)q=q.eq('size',selectedSize);if(selectedColor)q=q.eq('color',selectedColor);const {data}=await q.limit(1).maybeSingle();return data};const makeItem=async()=>{const v=await getVariant();if(!v)return toast('មិនមាន variant នេះទេ');if(Number(v.quantity)<state.qty)return toast('ស្តុកមិនគ្រប់');return {inventory_id:v.id,product_id:p.id,product_name:p.name,size:selectedSize,color:selectedColor,price:p.price,quantity:state.qty,image_url:image,max_stock:v.quantity}};$('addCart').onclick=async e=>{e.preventDefault();e.stopPropagation();const item=await makeItem();if(!item)return;const key=`${item.inventory_id}`;const old=state.cart.find(x=>String(x.inventory_id)===key);if(old)old.quantity=Math.min(Number(item.max_stock),Number(old.quantity)+state.qty);else state.cart.push(item);saveCart();toast('បានបន្ថែមទៅកន្ត្រក');};$('buyNow').onclick=async e=>{e.preventDefault();e.stopPropagation();const item=await makeItem();if(item){state.checkoutMode='buy-now';state.checkoutItems=[item];render('checkout')}}}
function renderCart(){setHeader('កន្ត្រកទំនិញ',true);if(!state.cart.length){page.innerHTML='<div class="empty-state large">🛒<h3>កន្ត្រកទំនិញទទេ</h3><p>សូមជ្រើសរើសផលិតផលជាមុនសិន</p><button id="shop" class="primary-action">ទៅទិញទំនិញ</button></div>';$('shop').onclick=()=>render('home');return}page.innerHTML=`<div class="cart-head"><h2>កន្ត្រក</h2><label><input id="all" type="checkbox" checked> ជ្រើសរើសទាំងអស់</label></div><div id="cartList">${state.cart.map((i,n)=>`<div class="cart-row" data-i="${n}"><input class="select-item" type="checkbox" checked><img src="${esc(i.image_url)}"><div class="cart-main"><b>${esc(i.product_name)}</b><small>${esc(i.size)} · ${esc(i.color)}</small><strong>${money(Number(i.price)*Number(i.quantity))}</strong><div class="row-actions"><button type="button" class="qminus">−</button><span>${i.quantity}</span><button type="button" class="qplus">+</button><button type="button" class="remove">លុប</button></div></div></div>`).join('')}</div><div class="cart-bottom"><div><small>សរុប</small><b id="selectedTotal">$0.00</b></div><button id="cartCheckout" class="primary-action">ទិញឥឡូវនេះ</button></div>`;const selected=new Set(state.cart.map((_,i)=>i));const update=()=>{$('selectedTotal').textContent=money([...selected].reduce((s,i)=>s+Number(state.cart[i].price)*Number(state.cart[i].quantity),0));$('all').checked=selected.size===state.cart.length};$('all').onchange=e=>{e.stopPropagation();selected.clear();if(e.target.checked)state.cart.forEach((_,i)=>selected.add(i));page.querySelectorAll('.select-item').forEach(x=>x.checked=e.target.checked);update()};page.querySelectorAll('.cart-row').forEach(row=>{const i=+row.dataset.i;row.querySelector('.select-item').onchange=e=>{e.stopPropagation();e.target.checked?selected.add(i):selected.delete(i);update()};row.querySelector('.qminus').onclick=e=>{e.stopPropagation();state.cart[i].quantity=Math.max(1,state.cart[i].quantity-1);saveCart();renderCart()};row.querySelector('.qplus').onclick=e=>{e.stopPropagation();state.cart[i].quantity=Math.min(Number(state.cart[i].max_stock||9999),state.cart[i].quantity+1);saveCart();renderCart()};row.querySelector('.remove').onclick=e=>{e.stopPropagation();state.cart.splice(i,1);saveCart();renderCart()}});$('cartCheckout').onclick=e=>{e.preventDefault();e.stopPropagation();const items=[...selected].map(i=>state.cart[i]);if(!items.length)return toast('សូមជ្រើសរើសទំនិញ');state.checkoutMode='cart';state.checkoutItems=items;render('checkout')};update()}
function renderCheckout(){setHeader(state.checkoutMode==='buy-now'?'បញ្ជាទិញឥឡូវនេះ':'បំពេញការបញ្ជាទិញ',true);const items=state.checkoutItems,total=items.reduce((s,i)=>s+Number(i.price)*Number(i.quantity),0);page.innerHTML=`<form id="checkoutForm" class="checkout-v2"><div class="checkout-title"><span>បញ្ជាទិញ</span><small>${items.length} មុខទំនិញ</small></div><div class="checkout-products">${items.map(i=>`<div class="checkout-item"><img src="${esc(i.image_url)}"><div><b>${esc(i.product_name)}</b><small>${esc(i.size)} · ${esc(i.color)} · x${i.quantity}</small></div><strong>${money(Number(i.price)*Number(i.quantity))}</strong></div>`).join('')}</div><section class="checkout-section"><h3>ព័ត៌មានដឹកជញ្ជូន</h3><label>ឈ្មោះ<input id="name" required autocomplete="name"></label><label>លេខទូរស័ព្ទ<input id="phone" required type="tel" autocomplete="tel"></label><label>អាសយដ្ឋាន<textarea id="address" required rows="3"></textarea></label></section><section class="checkout-section"><h3>ការបង់ប្រាក់</h3><label class="radio"><input type="radio" name="payment" value="khqr" checked> KHQR</label><label class="radio"><input type="radio" name="payment" value="cash"> ទូទាត់ពេលទទួលទំនិញ</label><div class="qr-box"><img id="qr" src="${esc(window.CHUCHUS_KHQR_IMAGE_URL||'')}" onerror="this.style.display='none'"><div id="qrEmpty">KHQR របស់ហាងនឹងបង្ហាញនៅទីនេះ</div></div></section><div class="checkout-total"><span>សរុប</span><b>${money(total)}</b></div><button id="placeOrder" class="primary-action" type="submit">ដាក់បញ្ជាទិញ · ${money(total)}</button></form>`;const form=$('checkoutForm');form.addEventListener('click',e=>e.stopPropagation());form.onsubmit=submitOrder}
async function submitOrder(e){e.preventDefault();e.stopImmediatePropagation();const user=tg?.initDataUnsafe?.user;if(!user?.id)return toast('សូមបើកតាម Telegram ដើម្បីបញ្ជាទិញ');const name=$('name').value.trim(),phone=$('phone').value.trim(),address=$('address').value.trim(),payment=document.querySelector('input[name="payment"]:checked')?.value||'khqr';if(!name||!phone||!address)return toast('សូមបំពេញព័ត៌មានឲ្យបានពេញលេញ');const btn=$('placeOrder');btn.disabled=true;try{const {data,error}=await supabase.rpc('place_order_atomic',{p_telegram_id:Number(user.id),p_username:user.username||null,p_first_name:name,p_phone:phone,p_address:address,p_payment_method:payment,p_items:state.checkoutItems.map(i=>({inventory_id:i.inventory_id,quantity:Number(i.quantity)}))});if(error)throw error;if(!data?.order_id)throw new Error('Order RPC មិនបានបញ្ជាក់លេខ order');if(state.checkoutMode==='cart'){const ids=new Set(state.checkoutItems.map(i=>String(i.inventory_id)));state.cart=state.cart.filter(i=>!ids.has(String(i.inventory_id)));saveCart()}else{const ids=new Set(state.checkoutItems.map(i=>String(i.inventory_id)));state.cart=state.cart.filter(i=>!ids.has(String(i.inventory_id)));saveCart()}page.innerHTML=`<div class="success-page"><div class="success-icon">✓</div><h2>បញ្ជាទិញបានជោគជ័យ</h2><p>លេខបញ្ជាទិញ</p><strong>${esc(data.order_number||data.order_id)}</strong><button id="done" class="primary-action">ត្រឡប់ទៅហាង</button></div>`;$('done').onclick=()=>render('home')}catch(err){console.error(err);toast(err.message||'មិនអាចបញ្ជាទិញបាន');btn.disabled=false}}
$('loading').style.display='none';$('app').style.display='block';loadCart();render('home');
